import { useState } from "react";
import 'rc-pagination/assets/index.css'
import type { AppProps } from 'next/app'
import { QueryClient, QueryClientProvider } from "react-query";
import { RecoilRoot } from "recoil";

import { GlobalStyle } from "../assets/styles/globalStyles";
import Head from "next/head";

function MyApp({Component, pageProps}: AppProps) {
    const [queryClient] = useState(() => new QueryClient({
        defaultOptions: {
            queries: {
                refetchOnWindowFocus: false
            }
        }
    }))

    return <>
        <Head>
            <title>Darqube</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap" rel="stylesheet"/>
        </Head>
        <GlobalStyle/><QueryClientProvider
        client={queryClient}><RecoilRoot><Component {...pageProps} /></RecoilRoot>
    </QueryClientProvider> </>
}

export default MyApp
