import type {NextPage} from 'next'
import Head from 'next/head'
import { PostsPage } from "../modules/posts/PostsPage";


const Home: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Darqube</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <PostsPage/>
        </div>
    )
}

export default Home
